apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-account-lookup-service
spec:
  type: NodePort 
  ports:
    {{- with .Values.accountLookUp }}
    - name: {{ .ports.containerAdminPort | quote }}
      port: {{ .ports.containerAdminPort }}
      targetPort: {{ .ports.containerAdminPort }}
      nodePort: {{ .ports.nodeAdminPort }}
    - name: {{ .ports.containerApiPort | quote }}
      port: {{ .ports.containerApiPort }}
      targetPort: {{ .ports.containerApiPort }}
      nodePort: {{ .ports.nodeApiPort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-account-lookup-service
status:
  loadBalancer: {}
