apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.dfsp1.config.dfspId }}-redis
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.dfsp1.config.dfspId }}-redis
  ports:
  - name: "redis-dfsp1-port"
    port: 6379
    targetPort: 6379
status:
  loadBalancer: {}
