apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.dfsp1.config.dfspId }}-backend"
spec:
  type: NodePort 
  ports:
    {{- with .Values.dfsp1 }}
    - name: {{ .ports.containerPort | quote }}
      port: {{ .ports.port }}
      targetPort: {{ .ports.containerPort }}
      nodePort: {{ .ports.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.dfsp1.config.dfspId }}-backend
status:
  loadBalancer: {}
