apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "2181"
    port: 2181
    targetPort: 2181
  - name: "29092"
    port: 29092
    targetPort: 29092
    nodePort: 31091
  selector:
    app: kafka
status:
  loadBalancer: {}
