apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ml-api-adapter
spec:
  type: NodePort
  ports:
    {{- with .Values.mlApiAdapter }}
    - name: {{ .ports.containerPort | quote }}
      port: {{ .ports.containerPort }}
      targetPort: {{ .ports.containerPort }}
      nodePort: {{ .ports.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-ml-api-adapter
status:
  loadBalancer: {}