apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ml-api-adapter
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ml-api-adapter
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ml-api-adapter
    spec:
      initContainers:
      - name: init-ml-api-adapter
        image: busybox:1.28
        command: ['sh','-c' ,'sleep 120']
      containers:
      - args:
        - sh
        - -c
        - node src/api/index.js
        env:
        - name: LOG_LEVEL
          value: info
        name: {{ .Release.Name }}-ml-api-adapter
        {{- with .Values.mlApiAdapter }}
        image: "{{ .image.name }}:{{ .image.version }}"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - apk --no-cache add curl
            - ;
            - curl
            - http://localhost:{{ .ports.containerPort }}/health
          failureThreshold: 10
          periodSeconds: 30
          timeoutSeconds: 20
        ports:
        - containerPort: {{ .ports.containerPort }}
        {{- end }}
        resources: {}
        volumeMounts:
          - name: config-volume
            mountPath: /opt/ml-api-adapter/config/default.json
            subPath: default.json
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: ml-api-adapter-configmap
status: {}
