apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simulator
spec:
  type: NodePort 
  ports:
    {{- with .Values.simulator }}
    - name: {{ .ports.containerPort | quote }}
      port: {{ .ports.containerPort }}
      targetPort: {{ .ports.containerPort }}
      nodePort: {{ .ports.nodePort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-simulator
status:
  loadBalancer: {}
